name: Keebdex Database Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches: ['main']

env:
  NODE_ENV: production
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  CF_IMAGES_API_KEY: ${{ secrets.CF_IMAGES_API_KEY }}
  CF_IMAGES_ACCOUNT_ID: ${{ secrets.CF_IMAGES_ACCOUNT_ID }}
  CF_IMAGES_ACCOUNT_HASH: ${{ secrets.CF_IMAGES_ACCOUNT_HASH }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  database-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create Google service account key
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: 'keebdex.json'
          json: ${{ env.GOOGLE_SERVICE_ACCOUNT }}

      - name: Sync data from Google Docs
        run: bun run gdocs-importer

      - name: Sync data from maker websites/APIs
        run: bun run maker-scraper

      - name: Sync new keycaps to database
        run: bun run sync-keycaps
