name: Keebdex Image Prune

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Runs at midnight on the first day of every month
  # push:
  #   branches: [ "main" ]

env:
  NODE_ENV: production
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  CF_IMAGES_API_KEY: ${{ secrets.CF_IMAGES_API_KEY }}
  CF_IMAGES_ACCOUNT_ID: ${{ secrets.CF_IMAGES_ACCOUNT_ID }}
  CF_IMAGES_ACCOUNT_HASH: ${{ secrets.CF_IMAGES_ACCOUNT_HASH }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  image-prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Prune Cloudflare Images
        run: bun run prune-images