name: Keebdex Image Prune

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # On the 1st of every month at midnight UTC
  push:
    branches: [ "main" ]

env:
  NODE_ENV: production
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  CF_IMAGES_API_KEY: ${{ secrets.CF_IMAGES_API_KEY }}
  CF_IMAGES_ACCOUNT_ID: ${{ secrets.CF_IMAGES_ACCOUNT_ID }}
  CF_IMAGES_ACCOUNT_HASH: ${{ secrets.CF_IMAGES_ACCOUNT_HASH }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  image-prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Prune Cloudflare Images
        run: yarn prune-images